### ISSUE TITLE
SQL.js - a port of SQLite to JavaScript

### ISSUE THREAD

**Issue by ns-1m** [litehelpers/Cordova-SQLitePlugin-legacy-iOS-broken-bug666#13]
You want more SQL in javascript, then probably you can hack this,

https://github.com/kripken/sql.js

to enchance the plugin.

What are people think about SQL.js

http://badassjs.com/post/18857332551/sql-js-sqlite-compiled-to-javascript-via-emscripten?d9fdf148

**Comment by brody2consult** [comment]
I do not see how SQL.js will work together with this plugin. SQL.js manipulates the data in memory and needs a driver to store its binary data on the file system. In addition, the penalty of manipulating the data in Javascript becomes worse on iOS since it does not benefit from the V8 JIT. Please let me know if there is something I have not thought of, otherwise I want to close this issue.

**Comment by brody2consult** [comment]
SQL.js is not relevant to this plugin, issue closed.
